language: go
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.40/hugo_0.40_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: BLTSNbFwlzkjX0AlJ52tg9S+33zMRkCISpnzJoIIbpraVo+NOjBzjiNIXSKjzRPIIK2vK3IsmzPPSro3FxX5V+MS7dfVRtleaIF4qamV2allrai5iL+n6rCMlHdIr+89RT1F9F190yHggjuS3kGNeiSFOvASOIqStIkoz5LQhE29OERyX/53TQmGg4VYRwzC0ipyuB/KMVojd+3MwPBJKZHb1tuf9c4Q4T36fBXs6PzN0hugoti1L3G5sZAPHmbIAjfacLXgFCZ0Ub1FLNKhkeihUdAOtFRd1oVS50KTF+Tz1HC1/o5elyVXE23MROt0t2fYKOpG4CzcnnARULE7aN4srpkKtsPqbFpUlJPFZdzCCEEb6ShTL8XDewTSmpgaoJuqsO2CLZ1zgyiG+wynN0mPOgHi+Rau5AaUhyWcJl26ghi/oDASWahZUN9tbD3aeuKhY189fhrw/MuNy4O9qkpcZA1MOM/Ze43R5zgxRec5JXUEHZhigKoGBtqUGMBDxMPpEf98JVFsWIBpSp2pJHSvIopp+6CgjtRpSWesOpCpwpkg+fHDZEdfvo9R7zwDBuOwiaB8C+67cx2x9tZ64J5135PDKhF8Q/EHm6uv16IWpChMh9cjV/kOujgsH33NQ2Y+/Wjd11kM60kliYz5OKo87lmmE/Hr2ezoqOSWN6c=
  - secure: ajp2mJERDxa6euIrV3bcIU5vNqmCirOG9elvIVvwzEX84lO5yoRKMS5CmmHMwlCRQvcX+IrnlqN3jZvRatj5rVQrTEWC4VyOntUy8p41JbjP+/SmuxIPgK08c7WnA99uagpaBRjQsfskrNIue3x4cYGj00h1s3NneH96m5DkqjsL4p/F3rmo/5A9o7B580XmVMsNsGs6ievj/1/67BEyFba3MODYkm0cARBS9RorMh+IFdiF+o0ayoUk/Z00cpq99UrgKufh812aZtee/nNmMQMQXOaU2c2Q735q+Iy3kzFKXMRFQg9fcTZpMvcUidbYuHfjZIkEPMFKf4uJzXoo8HivVO3bH3rQLwyxVR2G2kGvuttXy80fzC2nIjB4TgWGMtWmdx+esT4HzhQ8mjjulbtzaXnNsM7fFSjzKZWdPRtrR697iyodfAR41T0n2wM5SWcF1g43XsBrcE4jxYNMardGItl7RmiqSqdDVtYwPFgSfYalXyhdT/Pevfv1KtqUj06eZzy/KAy2D7G1AsTUglb+WLqHAYPe+oRq9wymWYEor6SMMNKN8kcjO3j5iLLBeL5QYtGYewGESzH5TzaZ1dzhGFXI0g17ERF0ieCmKRDPtTlB7cemQmzkeGmqj8qcTprzAJ0etD9FuYtgsrhGnjpoGcx5/V+1Jl1vvGQWYqk=
